tls:
  certificates:
    - certFile: /var/lib/tailscale/certs/n8n.tail60cd1d.ts.net.crt
      keyFile: /var/lib/tailscale/certs/n8n.tail60cd1d.ts.net.key
  stores:
    default:
      defaultCertificate:
        certFile: /var/lib/tailscale/certs/n8n.tail60cd1d.ts.net.crt
        keyFile: /var/lib/tailscale/certs/n8n.tail60cd1d.ts.net.key
